### ISSUE TITLE
Why best MobileNetV1?

### ISSUE THREAD

**Issue by daquexian** [Bowenwu1/MobileNetV1-PyTorch#1]
MobileNet v1 in GluonCV has 73.28% top-1 on ImageNet

https://gluon-cv.mxnet.io/model_zoo/classification.html

**Comment by Bowenwu1** [comment]
I just browsed GluonCV and it seems based on **MXNet**.
As far as we know, our MobileNetV1 has best top-1 among **PyTorch**.

**Comment by daquexian** [comment]
> I just browsed GluonCV and it seems based on **MXNet**.
> As far as we know, our MobileNetV1 has best top-1 among **PyTorch**.

@Bowenwu1 So please edit your description
> Maybe the Best MobileNetV1 on Github!

**Comment by Bowenwu1** [comment]
OK. I have changed it to "Maybe the Best MobileNetV1 **of PyTorch** on Github!"
